/*
 * mini_ai_parser.c
 * AI-Generated Recursive-Descent LL(1) Parser for Mini DSL
 *
 * Generated by: Cursor AI (Claude)
 * Lab 8 - LFTC
 *
 * Input: tokens.in (reserved tokens), pif.out (program internal form)
 * Output: Parse tree in parent-sibling table format + productions string
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* ============================================================
 * TOKEN DEFINITIONS
 * ============================================================ */
typedef enum
{
    T_EOF = 0,
    /* Keywords */
    T_LET,
    T_PRINT,
    T_IF,
    T_THEN,
    T_ELSE,
    T_END,
    T_AND,
    T_OR,
    /* Built-in functions */
    T_SIN,
    T_COS,
    T_SQRT,
    T_POW,
    /* Delimiters */
    T_LPAR,
    T_RPAR,
    T_COMMA,
    T_SEMI,
    /* Operators */
    T_ASSIGN,
    T_EQ,
    T_NEQ,
    T_LT,
    T_LE,
    T_GT,
    T_GE,
    T_PLUS,
    T_MINUS,
    T_MUL,
    T_DIV,
    /* Literals */
    T_ID,
    T_NUM,
    /* Error */
    T_UNKNOWN
} TokenType;

/* Token names for error messages */
static const char *token_names[] = {
    "EOF", "let", "print", "if", "then", "else", "end", "and", "or",
    "sin", "cos", "sqrt", "pow", "(", ")", ",", ";",
    "=", "==", "!=", "<", "<=", ">", ">=", "+", "-", "*", "/",
    "ID", "NUM", "UNKNOWN"};

/* ============================================================
 * GLOBAL STATE
 * ============================================================ */
static int *tokens = NULL;  /* Token array from PIF */
static int token_count = 0; /* Number of tokens */
static int token_pos = 0;   /* Current position */

static char *reserved[64]; /* Reserved tokens from tokens.in */
static int reserved_count = 0;

/* Parse tree node */
typedef struct
{
    char info[32];
    int parent;
    int right_sibling;
} TreeNode;

static TreeNode tree[2000];
static int node_count = 0;

/* Productions output */
static int print_productions = 1;

/* ============================================================
 * PARSE TREE FUNCTIONS
 * ============================================================ */
static int create_node(const char *info, int parent)
{
    int idx = ++node_count;
    strncpy(tree[idx].info, info, 31);
    tree[idx].info[31] = '\0';
    tree[idx].parent = parent;
    tree[idx].right_sibling = 0;
    return idx;
}

static void link_sibling(int node, int sibling)
{
    if (node > 0 && node <= node_count)
        tree[node].right_sibling = sibling;
}

/* ============================================================
 * LEXER FUNCTIONS
 * ============================================================ */
static TokenType current_token(void)
{
    return (token_pos < token_count) ? tokens[token_pos] : T_EOF;
}

static void advance(void)
{
    if (token_pos < token_count)
        token_pos++;
}

static void syntax_error(const char *expected)
{
    fprintf(stderr, "\n*** SYNTAX ERROR at token %d ***\n", token_pos + 1);
    fprintf(stderr, "Expected: %s\n", expected);
    fprintf(stderr, "Found: %s\n", token_names[current_token()]);
    exit(1);
}

static int accept(TokenType t)
{
    if (current_token() == t)
    {
        advance();
        return 1;
    }
    return 0;
}

static void expect(TokenType t)
{
    if (!accept(t))
    {
        syntax_error(token_names[t]);
    }
}

/* ============================================================
 * TOKEN MAPPING
 * ============================================================ */
static TokenType map_lexeme(const char *lex)
{
    /* Keywords */
    if (!strcmp(lex, "let"))
        return T_LET;
    if (!strcmp(lex, "print"))
        return T_PRINT;
    if (!strcmp(lex, "if"))
        return T_IF;
    if (!strcmp(lex, "then"))
        return T_THEN;
    if (!strcmp(lex, "else"))
        return T_ELSE;
    if (!strcmp(lex, "end"))
        return T_END;
    if (!strcmp(lex, "and"))
        return T_AND;
    if (!strcmp(lex, "or"))
        return T_OR;
    /* Functions */
    if (!strcmp(lex, "sin"))
        return T_SIN;
    if (!strcmp(lex, "cos"))
        return T_COS;
    if (!strcmp(lex, "sqrt"))
        return T_SQRT;
    if (!strcmp(lex, "pow"))
        return T_POW;
    /* Delimiters */
    if (!strcmp(lex, "("))
        return T_LPAR;
    if (!strcmp(lex, ")"))
        return T_RPAR;
    if (!strcmp(lex, ","))
        return T_COMMA;
    if (!strcmp(lex, ";"))
        return T_SEMI;
    /* Operators */
    if (!strcmp(lex, "="))
        return T_ASSIGN;
    if (!strcmp(lex, "=="))
        return T_EQ;
    if (!strcmp(lex, "!="))
        return T_NEQ;
    if (!strcmp(lex, "<"))
        return T_LT;
    if (!strcmp(lex, "<="))
        return T_LE;
    if (!strcmp(lex, ">"))
        return T_GT;
    if (!strcmp(lex, ">="))
        return T_GE;
    if (!strcmp(lex, "+"))
        return T_PLUS;
    if (!strcmp(lex, "-"))
        return T_MINUS;
    if (!strcmp(lex, "*"))
        return T_MUL;
    if (!strcmp(lex, "/"))
        return T_DIV;

    return T_UNKNOWN;
}

static char *trim(char *str)
{
    while (isspace((unsigned char)*str))
        str++;
    if (*str == 0)
        return str;
    char *end = str + strlen(str) - 1;
    while (end > str && isspace((unsigned char)*end))
        end--;
    end[1] = '\0';
    return str;
}

static void load_tokens_file(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f)
    {
        fprintf(stderr, "Error: Cannot open tokens file: %s\n", path);
        exit(1);
    }

    char line[256];
    while (fgets(line, sizeof(line), f))
    {
        char *s = trim(line);
        if (*s == '\0' || *s == '#')
            continue;

        /* Convert to lowercase */
        for (char *p = s; *p; p++)
            *p = tolower((unsigned char)*p);

        reserved[reserved_count++] = strdup(s);
    }
    fclose(f);
    printf("Loaded %d reserved tokens\n", reserved_count);
}

static void load_pif_file(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f)
    {
        fprintf(stderr, "Error: Cannot open PIF file: %s\n", path);
        exit(1);
    }

    char line[256];
    int capacity = 256;
    tokens = malloc(capacity * sizeof(int));

    while (fgets(line, sizeof(line), f))
    {
        int code, a, b;
        if (sscanf(line, "%d %d %d", &code, &a, &b) != 3)
            continue;

        if (token_count >= capacity)
        {
            capacity *= 2;
            tokens = realloc(tokens, capacity * sizeof(int));
        }

        TokenType t;
        if (code == 100)
        {
            t = T_ID;
        }
        else if (code == 101)
        {
            t = T_NUM;
        }
        else if (code >= 1 && code <= reserved_count)
        {
            t = map_lexeme(reserved[code - 1]);
            if (t == T_UNKNOWN)
            {
                fprintf(stderr, "Warning: Unknown lexeme '%s' (code %d)\n",
                        reserved[code - 1], code);
            }
        }
        else
        {
            fprintf(stderr, "Error: Invalid token code %d\n", code);
            exit(1);
        }

        tokens[token_count++] = t;
    }
    fclose(f);

    /* Append EOF */
    if (token_count >= capacity)
    {
        tokens = realloc(tokens, (capacity + 1) * sizeof(int));
    }
    tokens[token_count++] = T_EOF;

    printf("Loaded %d tokens from PIF\n", token_count - 1);
}

/* ============================================================
 * PARSER - FORWARD DECLARATIONS
 * ============================================================ */
static int parse_expr(int parent);
static int parse_stmt_list(int parent);

/* ============================================================
 * PARSER - EXPRESSIONS
 * ============================================================ */

/* arg_tail -> ',' expr arg_tail | ε */
static int parse_arg_tail(int parent)
{
    int n = create_node("arg_tail", parent);
    if (current_token() == T_COMMA)
    {
        if (print_productions)
            printf("arg_tail -> , expr arg_tail\n");
        int c = create_node(",", n);
        advance();
        int e = parse_expr(n);
        link_sibling(c, e);
        int t = parse_arg_tail(n);
        link_sibling(e, t);
    }
    else
    {
        if (print_productions)
            printf("arg_tail -> e\n");
        create_node("e", n);
    }
    return n;
}

/* arg_list -> expr arg_tail */
static int parse_arg_list(int parent)
{
    int n = create_node("arg_list", parent);
    if (print_productions)
        printf("arg_list -> expr arg_tail\n");
    int e = parse_expr(n);
    int t = parse_arg_tail(n);
    link_sibling(e, t);
    return n;
}

/* call -> func '(' arg_list_opt ')' */
static int parse_call(int parent)
{
    int n = create_node("call", parent);
    const char *fname = token_names[current_token()];
    if (print_productions)
        printf("call -> %s ( arg_list_opt )\n", fname);

    int f = create_node(fname, n);
    advance();
    int lp = create_node("(", n);
    expect(T_LPAR);
    link_sibling(f, lp);

    if (current_token() != T_RPAR)
    {
        int args = parse_arg_list(n);
        link_sibling(lp, args);
    }

    int rp = create_node(")", n);
    expect(T_RPAR);
    return n;
}

/* primary -> NUM | ID | '(' expr ')' | call */
static int parse_primary(int parent)
{
    int n = create_node("primary", parent);
    TokenType t = current_token();

    if (t == T_NUM)
    {
        if (print_productions)
            printf("primary -> NUM\n");
        create_node("NUM", n);
        advance();
    }
    else if (t == T_ID)
    {
        if (print_productions)
            printf("primary -> ID\n");
        create_node("ID", n);
        advance();
    }
    else if (t == T_LPAR)
    {
        if (print_productions)
            printf("primary -> ( expr )\n");
        int lp = create_node("(", n);
        advance();
        int e = parse_expr(n);
        link_sibling(lp, e);
        int rp = create_node(")", n);
        expect(T_RPAR);
        link_sibling(e, rp);
    }
    else if (t >= T_SIN && t <= T_POW)
    {
        if (print_productions)
            printf("primary -> call\n");
        parse_call(n);
    }
    else
    {
        syntax_error("NUM, ID, '(' or function");
    }
    return n;
}

/* unary -> '-' unary | primary */
static int parse_unary(int parent)
{
    int n = create_node("unary", parent);
    if (current_token() == T_MINUS)
    {
        if (print_productions)
            printf("unary -> - unary\n");
        int m = create_node("-", n);
        advance();
        int u = parse_unary(n);
        link_sibling(m, u);
    }
    else
    {
        if (print_productions)
            printf("unary -> primary\n");
        parse_primary(n);
    }
    return n;
}

/* mul_tail -> ('*' | '/') unary mul_tail | ε */
static int parse_mul_tail(int parent)
{
    int n = create_node("mul_tail", parent);
    TokenType t = current_token();
    if (t == T_MUL || t == T_DIV)
    {
        const char *op = (t == T_MUL) ? "*" : "/";
        if (print_productions)
            printf("mul_tail -> %s unary mul_tail\n", op);
        int o = create_node(op, n);
        advance();
        int u = parse_unary(n);
        link_sibling(o, u);
        int mt = parse_mul_tail(n);
        link_sibling(u, mt);
    }
    else
    {
        if (print_productions)
            printf("mul_tail -> e\n");
        create_node("e", n);
    }
    return n;
}

/* mul_expr -> unary mul_tail */
static int parse_mul_expr(int parent)
{
    int n = create_node("mul_expr", parent);
    if (print_productions)
        printf("mul_expr -> unary mul_tail\n");
    int u = parse_unary(n);
    int mt = parse_mul_tail(n);
    link_sibling(u, mt);
    return n;
}

/* add_tail -> ('+' | '-') mul_expr add_tail | ε */
static int parse_add_tail(int parent)
{
    int n = create_node("add_tail", parent);
    TokenType t = current_token();
    if (t == T_PLUS || t == T_MINUS)
    {
        const char *op = (t == T_PLUS) ? "+" : "-";
        if (print_productions)
            printf("add_tail -> %s mul_expr add_tail\n", op);
        int o = create_node(op, n);
        advance();
        int me = parse_mul_expr(n);
        link_sibling(o, me);
        int at = parse_add_tail(n);
        link_sibling(me, at);
    }
    else
    {
        if (print_productions)
            printf("add_tail -> e\n");
        create_node("e", n);
    }
    return n;
}

/* add_expr -> mul_expr add_tail */
static int parse_add_expr(int parent)
{
    int n = create_node("add_expr", parent);
    if (print_productions)
        printf("add_expr -> mul_expr add_tail\n");
    int me = parse_mul_expr(n);
    int at = parse_add_tail(n);
    link_sibling(me, at);
    return n;
}

/* cmp_tail -> cmp_op add_expr | ε */
static int parse_cmp_tail(int parent)
{
    int n = create_node("cmp_tail", parent);
    TokenType t = current_token();
    if (t >= T_EQ && t <= T_GE)
    {
        const char *ops[] = {"==", "!=", "<", "<=", ">", ">="};
        const char *op = ops[t - T_EQ];
        if (print_productions)
            printf("cmp_tail -> %s add_expr\n", op);
        int o = create_node(op, n);
        advance();
        int ae = parse_add_expr(n);
        link_sibling(o, ae);
    }
    else
    {
        if (print_productions)
            printf("cmp_tail -> e\n");
        create_node("e", n);
    }
    return n;
}

/* cmp_expr -> add_expr cmp_tail */
static int parse_cmp_expr(int parent)
{
    int n = create_node("cmp_expr", parent);
    if (print_productions)
        printf("cmp_expr -> add_expr cmp_tail\n");
    int ae = parse_add_expr(n);
    int ct = parse_cmp_tail(n);
    link_sibling(ae, ct);
    return n;
}

/* and_tail -> 'and' cmp_expr and_tail | ε */
static int parse_and_tail(int parent)
{
    int n = create_node("and_tail", parent);
    if (current_token() == T_AND)
    {
        if (print_productions)
            printf("and_tail -> and cmp_expr and_tail\n");
        int o = create_node("and", n);
        advance();
        int ce = parse_cmp_expr(n);
        link_sibling(o, ce);
        int at = parse_and_tail(n);
        link_sibling(ce, at);
    }
    else
    {
        if (print_productions)
            printf("and_tail -> e\n");
        create_node("e", n);
    }
    return n;
}

/* and_expr -> cmp_expr and_tail */
static int parse_and_expr(int parent)
{
    int n = create_node("and_expr", parent);
    if (print_productions)
        printf("and_expr -> cmp_expr and_tail\n");
    int ce = parse_cmp_expr(n);
    int at = parse_and_tail(n);
    link_sibling(ce, at);
    return n;
}

/* or_tail -> 'or' and_expr or_tail | ε */
static int parse_or_tail(int parent)
{
    int n = create_node("or_tail", parent);
    if (current_token() == T_OR)
    {
        if (print_productions)
            printf("or_tail -> or and_expr or_tail\n");
        int o = create_node("or", n);
        advance();
        int ae = parse_and_expr(n);
        link_sibling(o, ae);
        int ot = parse_or_tail(n);
        link_sibling(ae, ot);
    }
    else
    {
        if (print_productions)
            printf("or_tail -> e\n");
        create_node("e", n);
    }
    return n;
}

/* or_expr -> and_expr or_tail */
static int parse_or_expr(int parent)
{
    int n = create_node("or_expr", parent);
    if (print_productions)
        printf("or_expr -> and_expr or_tail\n");
    int ae = parse_and_expr(n);
    int ot = parse_or_tail(n);
    link_sibling(ae, ot);
    return n;
}

/* expr -> or_expr */
static int parse_expr(int parent)
{
    int n = create_node("expr", parent);
    if (print_productions)
        printf("expr -> or_expr\n");
    parse_or_expr(n);
    return n;
}

/* ============================================================
 * PARSER - STATEMENTS
 * ============================================================ */

/* else_part -> 'else' stmt_list | ε */
static int parse_else_part(int parent)
{
    int n = create_node("else_part", parent);
    if (current_token() == T_ELSE)
    {
        if (print_productions)
            printf("else_part -> else stmt_list\n");
        int e = create_node("else", n);
        advance();
        int sl = parse_stmt_list(n);
        link_sibling(e, sl);
    }
    else
    {
        if (print_productions)
            printf("else_part -> e\n");
        create_node("e", n);
    }
    return n;
}

/* if_stmt -> 'if' expr 'then' stmt_list else_part 'end' */
static int parse_if_stmt(int parent)
{
    int n = create_node("if_stmt", parent);
    if (print_productions)
        printf("if_stmt -> if expr then stmt_list else_part end\n");

    int k1 = create_node("if", n);
    expect(T_IF);
    int e = parse_expr(n);
    link_sibling(k1, e);
    int k2 = create_node("then", n);
    expect(T_THEN);
    link_sibling(e, k2);
    int sl = parse_stmt_list(n);
    link_sibling(k2, sl);
    int ep = parse_else_part(n);
    link_sibling(sl, ep);
    int k3 = create_node("end", n);
    expect(T_END);
    link_sibling(ep, k3);
    return n;
}

/* print_stmt -> 'print' expr ';' */
static int parse_print_stmt(int parent)
{
    int n = create_node("print_stmt", parent);
    if (print_productions)
        printf("print_stmt -> print expr ;\n");

    int k = create_node("print", n);
    expect(T_PRINT);
    int e = parse_expr(n);
    link_sibling(k, e);
    int s = create_node(";", n);
    expect(T_SEMI);
    link_sibling(e, s);
    return n;
}

/* let_stmt -> 'let' ID '=' expr ';' */
static int parse_let_stmt(int parent)
{
    int n = create_node("let_stmt", parent);
    if (print_productions)
        printf("let_stmt -> let ID = expr ;\n");

    int k = create_node("let", n);
    expect(T_LET);
    int id = create_node("ID", n);
    expect(T_ID);
    link_sibling(k, id);
    int eq = create_node("=", n);
    expect(T_ASSIGN);
    link_sibling(id, eq);
    int e = parse_expr(n);
    link_sibling(eq, e);
    int s = create_node(";", n);
    expect(T_SEMI);
    link_sibling(e, s);
    return n;
}

/* assign_stmt -> ID '=' expr ';' */
static int parse_assign_stmt(int parent)
{
    int n = create_node("assign_stmt", parent);
    if (print_productions)
        printf("assign_stmt -> ID = expr ;\n");

    int id = create_node("ID", n);
    expect(T_ID);
    int eq = create_node("=", n);
    expect(T_ASSIGN);
    link_sibling(id, eq);
    int e = parse_expr(n);
    link_sibling(eq, e);
    int s = create_node(";", n);
    expect(T_SEMI);
    link_sibling(e, s);
    return n;
}

/* stmt -> let_stmt | assign_stmt | print_stmt | if_stmt */
static int parse_stmt(int parent)
{
    int n = create_node("stmt", parent);
    TokenType t = current_token();

    if (t == T_LET)
    {
        if (print_productions)
            printf("stmt -> let_stmt\n");
        parse_let_stmt(n);
    }
    else if (t == T_ID)
    {
        if (print_productions)
            printf("stmt -> assign_stmt\n");
        parse_assign_stmt(n);
    }
    else if (t == T_PRINT)
    {
        if (print_productions)
            printf("stmt -> print_stmt\n");
        parse_print_stmt(n);
    }
    else if (t == T_IF)
    {
        if (print_productions)
            printf("stmt -> if_stmt\n");
        parse_if_stmt(n);
    }
    else
    {
        syntax_error("statement (let, print, if, or identifier)");
    }
    return n;
}

static int is_stmt_start(void)
{
    TokenType t = current_token();
    return t == T_LET || t == T_PRINT || t == T_IF || t == T_ID;
}

/* stmt_list -> stmt stmt_list | ε */
static int parse_stmt_list(int parent)
{
    int n = create_node("stmt_list", parent);
    if (is_stmt_start())
    {
        if (print_productions)
            printf("stmt_list -> stmt stmt_list\n");
        int s = parse_stmt(n);
        int sl = parse_stmt_list(n);
        link_sibling(s, sl);
    }
    else
    {
        if (print_productions)
            printf("stmt_list -> e\n");
        create_node("e", n);
    }
    return n;
}

/* program -> stmt_list */
static int parse_program(void)
{
    int n = create_node("program", 0);
    if (print_productions)
        printf("program -> stmt_list\n");
    parse_stmt_list(n);
    expect(T_EOF);
    return n;
}

/* ============================================================
 * OUTPUT
 * ============================================================ */
static void print_parse_tree(void)
{
    printf("\n");
    printf("================== PARSE TREE ==================\n");
    printf("%5s | %-15s | %6s | %7s\n", "Index", "Info", "Parent", "Sibling");
    printf("-------------------------------------------------\n");
    for (int i = 1; i <= node_count; i++)
    {
        printf("%5d | %-15s | %6d | %7d\n",
               i, tree[i].info, tree[i].parent, tree[i].right_sibling);
    }
    printf("-------------------------------------------------\n");
}

/* ============================================================
 * MAIN
 * ============================================================ */
int main(int argc, char **argv)
{
    printf("==============================================\n");
    printf("  Mini DSL Parser (AI-Generated)\n");
    printf("  Lab 8 - LFTC\n");
    printf("==============================================\n\n");

    if (argc < 3)
    {
        fprintf(stderr, "Usage: %s <tokens.in> <pif.out> [-q]\n", argv[0]);
        fprintf(stderr, "  -q  Quiet mode (no productions output)\n");
        return 1;
    }

    /* Check for quiet mode */
    if (argc >= 4 && strcmp(argv[3], "-q") == 0)
    {
        print_productions = 0;
    }

    /* Load input files */
    load_tokens_file(argv[1]);
    load_pif_file(argv[2]);

    printf("\n--- PRODUCTIONS ---\n");

    /* Parse */
    parse_program();

    /* Output tree */
    print_parse_tree();

    printf("\n*** PARSING SUCCESSFUL ***\n");
    printf("Total nodes: %d\n", node_count);

    /* Cleanup */
    free(tokens);
    for (int i = 0; i < reserved_count; i++)
        free(reserved[i]);

    return 0;
}
