Create database LibraryMg
go
use LibraryMg
go



CREATE TABLE Library
(ID INT NOT NULL PRIMARY KEY IDENTITY,
NrOfBooks INT,
Capacity INT
);



CREATE TABLE Book 
(ID INT NOT NULL PRIMARY KEY IDENTITY,
Title varchar(100) NOT NULL,
Author varchar(30) NOT NULL,
Publisher varchar(30),
Category varchar(50)
);



CREATE TABLE LibraryBook
(BookID INT NOT NULL,
LibraryID INT NOT NULL,
FOREIGN KEY (BookID) REFERENCES Book(ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (LibraryID) REFERENCES  Library(ID) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT pk_library_book PRIMARY KEY (BookID, LibraryID)
);



CREATE TABLE Borrowed 
(ID INT NOT NULL PRIMARY KEY IDENTITY,
IssuedDate DATE,
DueDate DATE,
BookID INT NOT NULL,
FOREIGN KEY (BookID) REFERENCES Book(ID) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE LibraryStaff 
(CNP INT NOT NULL PRIMARY KEY IDENTITY,
FirstName varchar(15) NOT NULL,
LastName varchar(15) NOT NULL,
HireDate DATE,
Email varchar(20),
LibraryID INT NOT NULL,
FOREIGN KEY (LibraryID) REFERENCES Library(ID) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE Location
(BookID INT NOT NULL PRIMARY KEY IDENTITY,
Shelf INT,
Row INT,
FOREIGN KEY (BookID) REFERENCES Book(ID) 
);



CREATE TABLE Address
(LID INT NOT NULL PRIMARY KEY IDENTITY,
City varchar(20),
Street varchar(20),
Number INT,
ZipCode INT
FOREIGN KEY (LID) REFERENCES Library(ID) 
);



CREATE TABLE Subscriber
(CNP INT NOT NULL PRIMARY KEY IDENTITY,
FirstName varchar(15) NOT NULL,
LastName varchar(15) NOT NULL,
NrRentedBooks INT
);



CREATE TABLE LibrarySubscriber
(LibraryID INT NOT NULL,
CNPSub INT NOT NULL,
FOREIGN KEY (LibraryID) REFERENCES Library(ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CNPSub) REFERENCES Subscriber(CNP) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT pk_library_subscriber PRIMARY KEY (LibraryID, CNPSub)
);



CREATE TABLE Subscription
(CNPSub INT NOT NULL PRIMARY KEY IDENTITY,
StartDate DATE,
EndDate DATE,
Price INT,
Availability BIT,
FOREIGN KEY (CNPSub) REFERENCES Subscriber(CNP)
);



