// src/index.ts
import "reflect-metadata";
import express, { Request, Response } from "express";
import cors from "cors";
import http from "http";
import { Server as SocketIOServer } from "socket.io";
import { AppDataSource } from "./data-source";
import directorsRouter from "./routes/directors";
import moviesRouter from "./routes/movies";
import fileRoutes from "./routes/files";
import { Director } from "./entity/Director";
import { Movie } from "./entity/Movie";

const PORT = 3001;
const app = express();
let autoGenerate = true;

app.use(cors());
app.use(express.json());
app.use("/directors", directorsRouter);
app.use("/movies", moviesRouter);
app.use("/files", fileRoutes);

app.post("/control/auto-generate", (req: Request, res: Response) => {
  autoGenerate = Boolean(req.body.enable);
  res.json({ autoGenerate });
});
app.get("/control/auto-generate", (_req, res) => {
  res.json({ autoGenerate });
});
app.get("/", (_req: Request, res: Response): void => {
  res.send("Server is running!");
});

const server = http.createServer(app);
const io = new SocketIOServer(server, { cors: { origin: "*" } });
io.on("connection", sock => {
  console.log("Client connected:", sock.id);
  sock.on("disconnect", () => console.log("Client disconnected"));
});

AppDataSource.initialize()
  .then(async () => {
    console.log("DataSource initialized");
    const dirRepo = AppDataSource.getRepository(Director);
    const movRepo = AppDataSource.getRepository(Movie);


    // only seed if no movies exist
    const existing = await movRepo.count();
    if (existing === 0) {
      console.log("⏳ Seeding database…");

      // your hard-coded list:
      const seed = [
        { title: "Interstellar", directorName: "Christopher Nolan", date: "7 November 2014", poster: "/interstellar.jpg" },
        { title: "Inception", directorName: "Christopher Nolan", date: "16 July 2010", poster: "https://...inception.jpg" },
        /* …and the rest of your 20 items… */
      ];

      // ensure each director
      const names = Array.from(new Set(seed.map(m => m.directorName)));
      await Promise.all(names.map(async name => {
        let d = await dirRepo.findOneBy({ name });
        if (!d) {
          d = dirRepo.create({ name });
          await dirRepo.save(d);
        }
      }));

      // save each movie directly
      for (const m of seed) {
        const director = await dirRepo.findOneBy({ name: m.directorName });
        if (!director) continue;  // should never happen
        await movRepo.save({
          title: m.title,
          date: m.date,
          poster: m.poster,
          director,           // now definitely a Director
        });
      }

      console.log("Seeding complete");
    } else {
      console.log(`ℹ️  ${existing} movies already in DB — skipping seed`);
    }
  })
  .catch(err => {
    console.error("DataSource / seeding error:", err);
  })
  .finally(() => {
    server.listen(PORT, () => {
      console.log(`Server listening on http://localhost:${PORT}`);
    });
  });

// optional: emit new auto-generated movies via WebSockets
setInterval(async () => {
  if (!autoGenerate) return;
  const movRepo = AppDataSource.getRepository(Movie);
  const dirs = await AppDataSource.getRepository(Director).find();
  if (dirs.length === 0) return;
  const randomDir = dirs[Math.floor(Math.random() * dirs.length)];
  // save directly—no .create(...) overload needed
  const currentCount = await movRepo.count();
  const saved = await movRepo.save({
    title: `AutoGenerated ${currentCount}`,
    date: new Date().toISOString().slice(0, 10),
    poster: `https://via.placeholder.com/200x300?text=Movie`,
    director: randomDir,
  });

  io.emit("newMovie", saved);
}, 7000);
