import React, { useEffect, useState, useCallback } from "react";
import Grid from "@mui/material/Grid";
import MovieCard from "./MovieCard";
import EditMovieModal from "./EditMovieModal";
import { Movie } from "../types/movie";
import { Director } from "../types/director";
import Button from "@mui/material/Button";
import TextField from "@mui/material/TextField";
import Box from "@mui/material/Box";
import { Alert, Pagination, CircularProgress, Snackbar } from "@mui/material";
import useOnlineStatus from "../hooks/useOnlineStatus";
import { queueOperation, processQueue, OfflineOperation } from "../utils/offlineQueue";
import { io } from "socket.io-client";
import { useAuth } from "../contexts/AuthContext";
import { apiFetch, API_URL } from "../utils/api";

// Global directors cache
let directorsCache: Director[] = [];
let directorsCacheTime = 0;
const CACHE_TTL = 5 * 60 * 1000; // 5 minutes in milliseconds

const MovieList = () => {
    const [movies, setMovies] = useState<Movie[]>([]);
    const [searchQuery, setSearchQuery] = useState<string>("");
    const [selectedMovie, setSelectedMovie] = useState<Movie | null>(null);
    const [isEditModalOpen, setEditModalOpen] = useState<boolean>(false);
    const [isAddModalOpen, setAddModalOpen] = useState<boolean>(false);
    const [directors, setDirectors] = useState<Director[]>([]);

    // Loading states
    const [isLoading, setIsLoading] = useState<boolean>(false);

    // Pagination state for the movie list.
    const [currentPage, setCurrentPage] = useState<number>(1);
    const [totalPages, setTotalPages] = useState<number>(1);
    // Fixed value for items per page
    const itemsPerPage = 10;

    // Offline and server status.
    const isOnline = useOnlineStatus();
    const [serverDown, setServerDown] = useState<boolean>(false);
    const { isAuthenticated, user } = useAuth();
    const [authError, setAuthError] = useState<boolean>(false);

    // Snackbar for user feedback
    const [snackbar, setSnackbar] = useState<{
        open: boolean;
        message: string;
        severity: 'success' | 'error' | 'info';
    }>({
        open: false,
        message: '',
        severity: 'info'
    });

    const showSnackbar = (message: string, severity: 'success' | 'error' | 'info' = 'info') => {
        setSnackbar({
            open: true,
            message,
            severity
        });
    };

    const hideSnackbar = () => {
        setSnackbar(prev => ({ ...prev, open: false }));
    };

    // Cache directors for better performance
    const fetchDirectors = useCallback(async () => {
        if (!isAuthenticated) {
            setAuthError(true);
            return [];
        }

        // Use cache if it's still valid
        const now = Date.now();
        if (directorsCache.length > 0 && now - directorsCacheTime < CACHE_TTL) {
            // Backend already filters by user for non-admin users
            setDirectors(directorsCache);
            return directorsCache;
        }

        try {
            const data = await apiFetch(
                `/directors?limit=100&noMovies=true&countOnly=true`
            );

            if (data.unauthorized) {
                setAuthError(true);
                return [];
            }

            // Backend already filters by user for non-admin users
            directorsCache = data.directors; // Store directors in cache
            directorsCacheTime = now;
            setDirectors(data.directors);
            return data.directors;
        } catch (err) {
            console.error("Failed to fetch directors:", err);
            return [];
        }
    }, [isAuthenticated, user?.id]);

    useEffect(() => {
        // Only fetch directors if authenticated
        if (isAuthenticated) {
            fetchDirectors();
        }
    }, [fetchDirectors, isAuthenticated]);

    useEffect(() => {
        // Connect to your backend Socket.IO server only if authenticated
        if (!isAuthenticated) return;

        const socket = io(API_URL, {
            reconnection: true,
            reconnectionAttempts: 3,
            timeout: 5000
        });

        // Listen for the newMovie event.
        socket.on("newMovie", (newMovie: Movie) => {
            console.log("Received new movie via socket:", newMovie);
            // Only refresh if it's not an auto-generated movie to avoid UI interference
            if (!newMovie.title.includes('AutoGenerated')) {
                fetchMovies();
            }
        });

        // Add error handling for socket connection
        socket.on("connect_error", (error) => {
            console.log("Socket connection error:", error);
            // Don't show errors to the user, just log them
        });

        // Cleanup the connection when the component unmounts.
        return () => {
            socket.disconnect();
        };
    }, [isAuthenticated]);

    // Fetch paginated movies.
    const fetchMovies = async () => {
        if (!isAuthenticated) {
            setAuthError(true);
            return;
        }

        setIsLoading(true);
        try {
            const data = await apiFetch(
                `/movies?page=${currentPage}&limit=${itemsPerPage}&director=${searchQuery}`
            );

            if (data.unauthorized) {
                setAuthError(true);
                return;
            }

            setMovies(data.movies);
            setTotalPages(data.totalPages);
            setServerDown(false);
        } catch (err) {
            console.error("Failed to fetch movies:", err);
            setServerDown(true);
        } finally {
            setIsLoading(false);
        }
    };

    // Initial fetch for both paginated movies and full movie list.
    useEffect(() => {
        if (isAuthenticated) {
            fetchMovies();
        }
    }, [currentPage, searchQuery, isAuthenticated]);

    // Process offline operations when back online and server is up.
    useEffect(() => {
        if (isOnline && !serverDown && isAuthenticated) {
            processQueue().then(() => {
                fetchMovies();
            });
        }
    }, [isOnline, serverDown, isAuthenticated]);

    const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setSearchQuery(event.target.value);
        setCurrentPage(1);
    };

    const handleOpenAddMovie = () => {
        setSelectedMovie({
            title: "",
            director: { id: 0, name: "" },
            date: "",
            poster: "",
        });
        setAddModalOpen(true);
    };

    const handleAddMovie = (newMovie: Movie) => {
        if (!isOnline || serverDown) {
            const op: OfflineOperation = { type: "add", payload: newMovie };
            queueOperation(op);
            setMovies((prev) => [...prev, { ...newMovie, id: Date.now() }]);
            setAddModalOpen(false);
            showSnackbar("Movie queued for creation when online", 'info');
            return;
        }

        // Validate that we have required data
        if (!newMovie.director?.id) {
            console.error("Cannot create movie: director is missing or invalid");
            showSnackbar("Please select a director before saving the movie.", 'error');
            return;
        }

        // Format the movie data for the backend
        const movieData = {
            title: newMovie.title,
            directorId: newMovie.director.id,
            date: newMovie.date,
            poster: newMovie.poster
        };

        console.log("Creating movie with data:", movieData);

        apiFetch('/movies', {
            method: "POST",
            body: JSON.stringify(movieData),
        })
            .then(async (savedMovie) => {
                console.log("Movie created successfully:", savedMovie);
                fetchMovies();
                setAddModalOpen(false);
                showSnackbar("Movie created successfully!", 'success');
            })
            .catch((err) => {
                console.error("Add error:", err);
                showSnackbar(`Failed to create movie: ${err.message || 'Unknown error'}`, 'error');
            });
    };

    const clearCache = async () => {
        try {
            // Clear frontend cache
            directorsCache = [];
            directorsCacheTime = 0;

            if (user?.role === 'admin') {
                await apiFetch('/movies/clear-cache', {
                    method: 'POST'
                });
                console.log('Backend cache cleared successfully');
            }
        } catch (err) {
            console.log('Backend cache clear failed (non-critical):', err);
        }
    };

    const handleDelete = (id: number) => {
        console.log(`Attempting to delete movie with ID: ${id}`);

        if (!isOnline || serverDown) {
            const op: OfflineOperation = { type: "delete", payload: { id } };
            queueOperation(op);
            setMovies((prev) => prev.filter((movie) => movie.id !== id));
            showSnackbar("Movie queued for deletion when online", 'info');
            return;
        }

        // Show loading state instead of optimistic update
        setIsLoading(true);

        console.log(`Making DELETE request to /movies/${id}`);

        apiFetch(`/movies/${id}`, {
            method: "DELETE"
        })
            .then(async (response) => {
                console.log(`Movie ${id} deleted successfully:`, response);
                // Clear cache and refresh the list
                await clearCache();
                // Force a complete refresh with a small delay to ensure backend is updated
                setTimeout(() => {
                    fetchMovies();
                }, 100);
                showSnackbar("Movie deleted successfully!", 'success');
            })
            .catch((err) => {
                console.error("Failed to delete movie:", err);
                console.error("Error details:", {
                    message: err.message,
                    status: err.status,
                    response: err.response
                });
                setIsLoading(false);
                showSnackbar(`Failed to delete movie: ${err.message || 'Unknown error'}`, 'error');
            });
    };

    const handleEdit = (movie: Movie) => {
        setSelectedMovie(movie);
        setEditModalOpen(true);
    };

    const handleUpdateMovie = (updatedMovie: Movie) => {
        console.log(`Attempting to update movie:`, updatedMovie);

        if (!isOnline || serverDown) {
            const op: OfflineOperation = { type: "update", payload: updatedMovie };
            queueOperation(op);
            setMovies((prev) =>
                prev.map((m) => (m.id === updatedMovie.id ? updatedMovie : m))
            );
            setEditModalOpen(false);
            showSnackbar("Movie queued for update when online", 'info');
            return;
        }

        // Validate that we have required data
        if (!updatedMovie.director?.id) {
            console.error("Cannot update movie: director is missing or invalid");
            showSnackbar("Please select a director before saving the movie.", 'error');
            return;
        }

        if (!updatedMovie.id) {
            console.error("Cannot update movie: movie ID is missing");
            showSnackbar("Cannot update movie: invalid movie data.", 'error');
            return;
        }

        // Format the movie data for the backend
        const movieData = {
            title: updatedMovie.title,
            directorId: updatedMovie.director.id,
            date: updatedMovie.date,
            poster: updatedMovie.poster
        };

        console.log("Updating movie with data:", movieData);
        console.log(`Making PATCH request to /movies/${updatedMovie.id}`);

        apiFetch(`/movies/${updatedMovie.id}`, {
            method: "PATCH",
            body: JSON.stringify(movieData),
        })
            .then(async (savedMovie) => {
                console.log("Movie updated successfully:", savedMovie);
                // Clear cache and refresh the list
                await clearCache();
                // Force a complete refresh with a small delay to ensure backend is updated
                setTimeout(() => {
                    fetchMovies();
                }, 100);
                setEditModalOpen(false);
                showSnackbar("Movie updated successfully!", 'success');
            })
            .catch((err) => {
                console.error("Failed to update movie:", err);
                console.error("Update error details:", {
                    message: err.message,
                    status: err.status,
                    response: err.response,
                    movieData: movieData,
                    updatedMovie: updatedMovie
                });
                showSnackbar(`Failed to update movie: ${err.message || 'Unknown error'}`, 'error');
            });
    };

    const handlePageChange = (event: React.ChangeEvent<unknown>, page: number) => {
        setCurrentPage(page);
    };

    // Render status banners for offline and server issues.
    const renderStatusBanner = () => {
        if (!isOnline) {
            return (
                <Box sx={{ backgroundColor: "red", color: "white", p: 1, textAlign: "center" }}>
                    Your internet connection is down.
                </Box>
            );
        }
        if (isOnline && serverDown) {
            return (
                <Box sx={{ backgroundColor: "orange", color: "black", p: 1, textAlign: "center" }}>
                    Our server is unreachable. You're in offline mode.
                </Box>
            );
        }
        return null;
    };

    if (authError) {
        return (
            <Alert severity="info" sx={{ mt: 2, mb: 2 }}>
                Please log in to view and manage movies
            </Alert>
        );
    }

    return (
        <>
            {renderStatusBanner()}

            <Box display="flex" justifyContent="space-between" alignItems="center" mb={2}>
                <Box>
                    <Button
                        variant="contained"
                        sx={{ backgroundColor: "black", color: "white", "&:hover": { backgroundColor: "#333" } }}
                        onClick={handleOpenAddMovie}
                    >
                        Add Movie
                    </Button>
                </Box>
                <TextField
                    label="Search by Director"
                    variant="outlined"
                    value={searchQuery}
                    onChange={handleSearchChange}
                />
            </Box>

            <Grid container spacing={2}>
                {isLoading && movies.length === 0 ? (
                    <Box display="flex" justifyContent="center" width="100%" p={4}>
                        <CircularProgress />
                    </Box>
                ) : movies.length > 0 ? (
                    movies.map((movie) => {
                        const getYear = (datestring: string): number => {
                            const parsed = new Date(datestring);
                            if (isNaN(parsed.getTime())) {
                                const yearMatch = datestring.match(/\d{4}$/);
                                return yearMatch ? Number(yearMatch[0]) : 0;
                            }
                            return parsed.getFullYear();
                        };

                        const years = movies.map((m) => getYear(m.date));
                        const minYear = Math.min(...years);
                        const maxYear = Math.max(...years);
                        const year = getYear(movie.date);

                        return (
                            <Grid item key={movie.id}>
                                <MovieCard
                                    title={movie.title}
                                    director={movie.director?.name || 'Unknown Director'}
                                    date={movie.date}
                                    poster={movie.poster}
                                    isEarliest={year === minYear}
                                    isLatest={year === maxYear}
                                    onEdit={() => handleEdit(movie)}
                                    onDelete={() => movie.id !== undefined && handleDelete(movie.id)}
                                />
                            </Grid>
                        );
                    })
                ) : (
                    <Box p={2} width="100%" textAlign="center">
                        <p>No movies found.</p>
                    </Box>
                )}
            </Grid>

            <Box display="flex" justifyContent="center" mt={2}>
                <Pagination
                    count={totalPages}
                    page={currentPage}
                    onChange={handlePageChange}
                    color="primary"
                    disabled={isLoading}
                />
            </Box>

            {isEditModalOpen && selectedMovie && (
                <EditMovieModal
                    movie={selectedMovie}
                    onSave={handleUpdateMovie}
                    onClose={() => setEditModalOpen(false)}
                    cachedDirectors={directors}
                />
            )}

            {isAddModalOpen && selectedMovie && (
                <EditMovieModal
                    movie={selectedMovie}
                    onSave={handleAddMovie}
                    onClose={() => setAddModalOpen(false)}
                    cachedDirectors={directors}
                />
            )}

            <Snackbar
                open={snackbar.open}
                autoHideDuration={4000}
                onClose={hideSnackbar}
                anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
            >
                <Alert
                    onClose={hideSnackbar}
                    severity={snackbar.severity}
                    sx={{ width: '100%' }}
                >
                    {snackbar.message}
                </Alert>
            </Snackbar>
        </>
    );
};

export default MovieList;
